version: '3.3'

services:
    pm4pydistr_master:
      container_name: pm4pydistr_master
      image: javert899/pm4pydistr:master_docker
      restart: always
      environment:
        pm4pydistr--type: master
        pm4pydistr--conf: master
        pm4pydistr--port: 5001
      ports:
        - "6001:5001"
      volumes:
        - ./master:/master

    pm4pydistr_slave1:
      container_name: pm4pydistr_slave1
      image: javert899/pm4pydistr:slave_docker
      restart: always
      environment:
        pm4pydistr--type: slave
        pm4pydistr--conf: slave1
        pm4pydistr--port: 5002
        pm4pydistr--master-host: pm4pydistr_master
        pm4pydistr--master-port: 5001
      ports:
        - "6002:5002"
      volumes:
        - ./master:/master
      depends_on:
        - 'pm4pydistr_master'

    pm4pydistr_slave2:
      container_name: pm4pydistr_slave2
      image: javert899/pm4pydistr:slave_docker
      restart: always
      environment:
        pm4pydistr--type: slave
        pm4pydistr--conf: slave2
        pm4pydistr--port: 5003
        pm4pydistr--master-host: pm4pydistr_master
        pm4pydistr--master-port: 5001
      ports:
        - "6003:5003"
      volumes:
        - ./master:/master
      depends_on:
        - 'pm4pydistr_master'