KEYPHRASE = "hello"
PYTHON_PATH = "python3"
BASE_FOLDER_LIST_OPTIONS = ["master", "/opt/pm4pydistr-share"]

THIS_HOST = "127.0.0.1"
PORT = 5001
MASTER_HOST = "127.0.0.1"
MASTER_PORT = 5001
CONF = "local"

PARAMETERS_TYPE = "--type"
PARAMETERS_PORT = "--port"
PARAMETERS_MASTER_HOST = "--master-host"
PARAMETERS_MASTER_PORT = "--master-port"
PARAMETERS_CONF = "--conf"
PARAMETERS_HOST = "--host"

SLEEPING_TIME = 30
SESSION_EXPIRATION = 70
